# Generated by Django 2.1.2 on 2018-10-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20181025_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='_html',
            field=models.TextField(default='', verbose_name='태그가 HTML화된 댓글 내용'),
            preserve_default=False,
        ),
    ]
